# Generated by Django 5.0.2 on 2024-02-21 10:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AI_Models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Короткое название",
                    ),
                ),
                (
                    "mission",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Назначение",
                    ),
                ),
                (
                    "link_github",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Ссылка на github",
                    ),
                ),
                (
                    "ai_model",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ai_model/",
                        verbose_name="Ссылка для загрузки",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Версия XML"
                    ),
                ),
                (
                    "date_public",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "date_upload",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Дата загрузки на сайт",
                    ),
                ),
                (
                    "date_unused",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Дата прекращения использования",
                    ),
                ),
            ],
            options={
                "verbose_name": "Нейросеть для преобразования",
                "verbose_name_plural": "Нейросети для преобразования",
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploaded_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XMLSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Короткое название",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("building", "Этап проектирования"),
                            ("exploitation", "Этап строительства"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Этап",
                    ),
                ),
                (
                    "file_schem_xsl",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="xml_schemas/",
                        verbose_name="Файл XML схемы (XSL)",
                    ),
                ),
                (
                    "file_schem_xsd",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="xml_schemas/",
                        verbose_name="Файл XML схемы (XSD)",
                    ),
                ),
                (
                    "file_annot",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="xml_schemas/",
                        verbose_name="Файл аннотации (PDF)",
                    ),
                ),
                (
                    "date_public",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "date_upload",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Дата загрузки на сайт",
                    ),
                ),
                (
                    "date_unused",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Дата прекращения использования",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Версия XML"
                    ),
                ),
                (
                    "normative",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Норматив"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Ссылка"
                    ),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.ai_models",
                        verbose_name="Модель для преобразования",
                    ),
                ),
            ],
            options={
                "verbose_name": "XML схема",
                "verbose_name_plural": "XML схемы",
            },
        ),
    ]
