# Generated by Django 5.0.2 on 2024-06-17 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="uploaded_by",
        ),
    ]
