# Generated by Django 5.0.2 on 2024-06-17 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_uploadedfile_name_uploadedfile_uploaded_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
