# Generated by Django 5.0.2 on 2024-02-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap_test", "0002_ai_models_alter_xmlschema_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xmlschema",
            name="file_annot",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="xml_schemas/",
                verbose_name="Файл аннотации (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="xmlschema",
            name="file_schem",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="xml_schemas/",
                verbose_name="Файл XML схемы (XSL)",
            ),
        ),
    ]
