# Generated by Django 5.0.2 on 2024-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap_test", "0003_alter_xmlschema_file_annot_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="xmlschema",
            old_name="file_schem",
            new_name="file_schem_xsl",
        ),
        migrations.AddField(
            model_name="xmlschema",
            name="file_schem_xsd",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="xml_schemas/",
                verbose_name="Файл XML схемы (XSD)",
            ),
        ),
    ]
