# Generated by Django 5.0.2 on 2024-02-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap_test", "0004_rename_file_schem_xmlschema_file_schem_xsl_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploaded_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
