# Generated by Django 5.0.2 on 2024-02-21 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bootstrap_test", "0005_uploadedfile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xmlschema",
            name="ai_model",
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
        migrations.DeleteModel(
            name="AI_Models",
        ),
        migrations.DeleteModel(
            name="XMLSchema",
        ),
    ]
